item {
     id: 1
     name: 'a'
}
item {
     id: 2
     name: 'b'
}
item {
     id: 3
     name: 'c'
}
item {
     id: 4
     name: 'd'
}
item {
     id: 5
     name: 'e'
}
item {
     id: 6
     name: 'f'
}
item {
     id: 7
     name: 'i'
}
item {
     id: 8
     name: 'k'
}
item {
     id: 9
     name: 'l'
}
item {
     id: 10
     name: 'm'
}
item {
     id: 11
     name: 'n'
}
item {
     id: 12
     name: 'o'
}
item {
     id: 13
     name: 'p'
}
item {
     id: 14
     name: 'q'
}
item {
     id: 15
     name: 'r'
}
item {
     id: 16
     name: 't'
}
item {
     id: 17
     name: 'u'
}
item {
     id: 18
     name: 'v'
}
item {
     id: 19
     name: 'w'
}
item {
     id: 20
     name: 'x'
}
item {
     id: 21
     name: 'y'
}
item {
     id: 22
     name: 'espacio'
}
item {
     id: 23
     name: 'parar'
}
